# Site Settings
title: HeartBits
url: 'https://heartbits.pt/'
baseurl:
date: NOVEMBER 2018

# Links
email: geral@heartbits.pt
facebook: HackathonHeartbits
github: #
twitter: #
previous_edition: https://2017.heartbits.pt

# Tracker
analytics: #

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-slim
  - jemoji

# Reading Files
include:
  - _pages
exclude:
  - .gitignore
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Build settings
encoding: "utf-8"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Slim
slim:
  pretty: true
  format: html5